version: '3.7'
services:
  node:
    restart: always
    build: .
    ports:
      - 80:8002
    depends_on:
      - mongo
    volumes:
      - ./:/code
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
    links:
      - mongo
volumes:
 mongodb:

