version: '3.7'
services:
  node:
    image: seanhong2000/shopping
    build: .
    ports:
      - 8002:8002
    networks:
      - net

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    networks:
      - net
    ports:
      - 8083:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_USERNAME=root
      - ME_CONFIG_MONGODB_PASSWORD=example

networks:
 net:
  external: 
   name: mon_net
